from enum import StrEnum


class DealStatus(StrEnum):
    PENDING = "pending"
    PAID = "paid"
    IN_PROGRESS = "in_progress"
    DELIVERED = "delivered"
    COMPLETED = "completed"
    DISPUTED = "disputed"
    REFUNDED = "refunded"
    CANCELLED = "cancelled"


# per_query 渠道且金额低于此阈值时可启用 auto_confirm
AUTO_CONFIRM_AMOUNT_THRESHOLD_CENTS = 5000
AUTO_CONFIRM_DELAY_HOURS = 24
IDEMPOTENCY_TTL_HOURS = 24
PER_QUERY_CHANNEL = "per_query"

DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

WEBHOOK_EVENT_STATUS_CHANGED = "deals.status_changed"
WEBHOOK_EVENT_MESSAGE_CREATED = "deals.message_created"

class DealMessageSenderRole(StrEnum):
    SYSTEM = "system"
    BUYER = "buyer"
    SELLER = "seller"
    AGENT = "agent"


class DealMessageKind(StrEnum):
    TEXT = "text"
    DELIVERY = "delivery"
    STATUS = "status"

# deals 模块错误码（45000–45999）
ERR_DEAL_NOT_FOUND = 45001
ERR_DEAL_FORBIDDEN = 45002
ERR_DEAL_INVALID_STATUS = 45003
ERR_DEAL_MATCH_LOG_NOT_FOUND = 45004
ERR_DEAL_PAIR_MISMATCH = 45005
ERR_DEAL_VERSION_CONFLICT = 45006
ERR_DEAL_DELIVERY_REQUIRED = 45007
ERR_DEAL_DISPUTE_REASON_REQUIRED = 45008
ERR_DEAL_CREATE_INVALID = 45009
ERR_DEAL_WEBHOOK_NOT_FOUND = 45010
ERR_DEAL_NOT_PENDING = 45011
ERR_DEAL_REFUND_FORBIDDEN = 45012
ERR_DEAL_MESSAGE_FORBIDDEN = 45013
ERR_DEAL_MESSAGE_EMPTY = 45014
ERR_DEAL_MESSAGE_CLOSED = 45015
